# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the RTK IPC(Inter Process Communication) drivers.
#

# RTK IPC(Inter Process Communication) drivers for ameba
obj-$(CONFIG_IPC_RTK_AMEBA) += ameba_ipc.o