obj-$(CONFIG_ARM)		+= mrdump_arm.o
obj-$(CONFIG_ARM64)		+= mrdump_arm64.o
obj-$(CONFIG_MTD)		+= mrdump_mtd.o
obj-$(CONFIG_ARM)		+= mrdump_platform_ameba.o

obj-y				+= mrdump.o mrdump_mini.o mrdump_rom.o mrdump_file.o

ccflags-y += -I$(srctree)/arch/arm/include
