# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_AMEBASMART) += \
	rtl8730eah-va6-generic.dtb \
	rtl8730eah-va6-full.dtb \
	rtl8730eah-va6-recovery.dtb \
	rtl8730eam-va6-generic.dtb \
	rtl8730eam-va6-full.dtb \
	rtl8730eam-va6-recovery.dtb \
	rtl8730elm-va7-generic.dtb \
	rtl8730elm-va7-full.dtb \
	rtl8730elm-va7-recovery.dtb \
	rtl8730elm-va8-generic.dtb \
	rtl8730elm-va8-full.dtb \
	rtl8730elm-va8-recovery.dtb
