// SPDX-License-Identifier: GPL-2.0-only
/*
* Realtek DMAC support
*
* Copyright (C) 2023, Realtek Corporation. All rights reserved.
*/

#ifndef _DT_BINDINGS_REALTEK_AMEBA_DMAC_H
#define _DT_BINDINGS_REALTEK_AMEBA_DMAC_H

/** @defgroup GDMA0_HS_Interface_definition GDMA HandShake Interface Definition
  * @{
  */
#define GDMA_HANDSHAKE_INTERFACE_UART0_TX		(0)
#define GDMA_HANDSHAKE_INTERFACE_UART0_RX		(1)
#define GDMA_HANDSHAKE_INTERFACE_UART1_TX		(2)
#define GDMA_HANDSHAKE_INTERFACE_UART1_RX		(3)
#define GDMA_HANDSHAKE_INTERFACE_UART2_TX		(4)
#define GDMA_HANDSHAKE_INTERFACE_UART2_RX		(5)
#define GDMA_HANDSHAKE_INTERFACE_SPI0_TX		(6)
#define GDMA_HANDSHAKE_INTERFACE_SPI0_RX		(7)
#define GDMA_HANDSHAKE_INTERFACE_SPI1_TX		(8)
#define GDMA_HANDSHAKE_INTERFACE_SPI1_RX		(9)
#define GDMA_HANDSHAKE_INTERFACE_QSPI_TX		(10)
#define GDMA_HANDSHAKE_INTERFACE_SPIC_TX		(11)
#define GDMA_HANDSHAKE_INTERFACE_SPIC_RX		(12)

#define GDMA_HANDSHAKE_INTERFACE_SPORT0F0_TX		(13)
#define GDMA_HANDSHAKE_INTERFACE_SPORT0F1_TX		(14)
#define GDMA_HANDSHAKE_INTERFACE_SPORT0F0_RX		(15)
#define GDMA_HANDSHAKE_INTERFACE_SPORT0F1_RX		(16)

#define GDMA_HANDSHAKE_INTERFACE_SPORT1F0_TX		(17)
#define GDMA_HANDSHAKE_INTERFACE_SPORT1F1_TX		(18)
#define GDMA_HANDSHAKE_INTERFACE_SPORT1F0_RX		(19)
#define GDMA_HANDSHAKE_INTERFACE_SPORT1F1_RX		(20)

#define GDMA_HANDSHAKE_INTERFACE_SPORT2F0_TX		(21)
#define GDMA_HANDSHAKE_INTERFACE_SPORT2F1_TX		(22)
#define GDMA_HANDSHAKE_INTERFACE_SPORT2F0_RX		(23)
#define GDMA_HANDSHAKE_INTERFACE_SPORT2F1_RX		(24)

#define GDMA_HANDSHAKE_INTERFACE_SPORT3F0_TX		(25)
#define GDMA_HANDSHAKE_INTERFACE_SPORT3F1_TX		(26)
#define GDMA_HANDSHAKE_INTERFACE_SPORT3F0_RX		(27)
#define GDMA_HANDSHAKE_INTERFACE_SPORT3F1_RX		(28)

#define GDMA_HANDSHAKE_INTERFACE_LEDC_TX		(29)
#define GDMA_HANDSHAKE_INTERFACE_Zigbee_TX		(30)
#define GDMA_HANDSHAKE_INTERFACE_Zigbee_RX		(31)

#define GDMA_HANDSHAKE_INTERFACE_UART3_TX		(32)
#define GDMA_HANDSHAKE_INTERFACE_UART3_RX		(33)
#define GDMA_HANDSHAKE_INTERFACE_I2C0_TX		(NULL)
#define GDMA_HANDSHAKE_INTERFACE_I2C0_RX		(NULL)
#define GDMA_HANDSHAKE_INTERFACE_ADC_RX			(NULL)
#define GDMA_HANDSHAKE_INTERFACE_AUDIO_TX		(NULL)
#define GDMA_HANDSHAKE_INTERFACE_AUDIO_RX		(NULL)
/**
  * @}
  */
/** @defgroup GDMA1_HS_Interface_definition GDMA HandShake Interface Definition.
  ** @brief this definition is not supported in the amebaD
  * @{
  */
#define GDMA_HANDSHAKE_TIMER_CAPTURE_UP			(0)
#define GDMA_HANDSHAKE_TIMER_CAPTURE_CH0		(1)
#define GDMA_HANDSHAKE_TIMER_PWM_UP			(2)
#define GDMA_HANDSHAKE_TIMER_PWM_CH0			(3)
#define GDMA_HANDSHAKE_TIMER_PWM_CH1			(4)
#define GDMA_HANDSHAKE_TIMER_PWM_CH2			(5)
#define GDMA_HANDSHAKE_TIMER_PWM_CH3			(6)
#define GDMA_HANDSHAKE_TIMER_PWM_CH4			(7)
#define GDMA_HANDSHAKE_TIMER_PWM_CH5			(8)
/**
  * @}
  */

#endif
