// SPDX-License-Identifier: GPL-2.0-only
/*
* Realtek ALSA support
*
* Copyright (C) 2021, Realtek Corporation. All rights reserved.
*/

#ifndef _RTL8710B_GDMA_H_
#define _RTL8710B_GDMA_H_

#include <linux/types.h>

/** @defgroup  GDMA-AUDIO HandShake Interface Definition
  * @{
  */

#define GDMA_HANDSHAKE_INTERFACE_SPORT0F0_TX	(13)
#define GDMA_HANDSHAKE_INTERFACE_SPORT0F1_TX	(14)
#define GDMA_HANDSHAKE_INTERFACE_SPORT0F0_RX	(15)
#define GDMA_HANDSHAKE_INTERFACE_SPORT0F1_RX	(16)

#define GDMA_HANDSHAKE_INTERFACE_SPORT1F0_TX	(17)
#define GDMA_HANDSHAKE_INTERFACE_SPORT1F1_TX	(18)
#define GDMA_HANDSHAKE_INTERFACE_SPORT1F0_RX	(19)
#define GDMA_HANDSHAKE_INTERFACE_SPORT1F1_RX	(20)

#define GDMA_HANDSHAKE_INTERFACE_SPORT2F0_TX	(21)
#define GDMA_HANDSHAKE_INTERFACE_SPORT2F1_TX	(22)
#define GDMA_HANDSHAKE_INTERFACE_SPORT2F0_RX	(23)
#define GDMA_HANDSHAKE_INTERFACE_SPORT2F1_RX	(24)

#define GDMA_HANDSHAKE_INTERFACE_SPORT3F0_TX	(25)
#define GDMA_HANDSHAKE_INTERFACE_SPORT3F1_TX	(26)
#define GDMA_HANDSHAKE_INTERFACE_SPORT3F0_RX	(27)
#define GDMA_HANDSHAKE_INTERFACE_SPORT3F1_RX	(28)

#define GDMA_HANDSHAKE_INTERFACE_ADC_RX			(NULL)
#define GDMA_HANDSHAKE_INTERFACE_AUDIO_TX		(NULL)
#define GDMA_HANDSHAKE_INTERFACE_AUDIO_RX		(NULL)

#endif //_RTL8710B_GDMA_H_

/******************* (C) COPYRIGHT 2016 Realtek Semiconductor *****END OF FILE****/