snd-soc-realtek-clock-objs := ameba_audio_clock.o ameba_audio_clock_driver.o
snd-soc-realtek-i2s-objs := ameba_sport.o sport.o
snd-soc-realtek-dma-objs := ameba_sport.o dma.o
snd-soc-realtek-rtl8730e-machine-objs := machine.o

obj-$(CONFIG_SND_SOC_SPORT_RTK_AMEBA) += snd-soc-realtek-clock.o
obj-$(CONFIG_SND_SOC_SPORT_RTK_AMEBA) += snd-soc-realtek-i2s.o
obj-$(CONFIG_SND_SOC_DMA_RTK_AMEBA) += snd-soc-realtek-dma.o
obj-$(CONFIG_SND_SOC_RTK_AMEBA) += snd-soc-realtek-rtl8730e-machine.o

