dtb-$(CONFIG_ARCH_AMEBASMART) += \
	rtl8730elh-va7-generic.dtb \
	rtl8730elh-va7-full.dtb \
	rtl8730elh-va7-ranging.dtb \
	rtl8730elh-va7-recovery.dtb \
	rtl8730elh-va8-generic.dtb \
	rtl8730elh-va8-full.dtb \
	rtl8730elh-va8-recovery.dtb
