# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Realtek SPIC drivers.
#

obj-$(CONFIG_SPI_REALTEK_RXI312)	+= spi-realtek-rxi312.o
obj-$(CONFIG_SPIC_RTK_AMEBA_RXI312)	+= spi-rxi312-nand.o spi-rxi312-nor.o
